#!/usr/bin/env python3
"""Generate assets for the tunnel eye-candy view.

Classic demoscene tunnel: a per-pixel polar lookup table (angle around the
tunnel axis, depth along it) plus a tileable brightness texture. At runtime
each output pixel is two LUT reads + a texture fetch + an audio-animated
palette lookup, fused straight into the QSPI blit — no framebuffer.

LUT is computed at HALF resolution (320x86, pixel-doubled 2x2 at runtime)
and stored column-major (index = hx*86 + hy) to match the portrait scan
order of the blit. Each entry packs angle (low byte) and depth (high byte);
depth also selects one of 8 baked fog levels (depth>>5).

Outputs: src/ui/assets/tunnel_lut.c, tunnel_tex.c (+ tunnel_assets.h).
"""

import math
import random

from gen_vu_assets import OUT_DIR

HALF_W, HALF_H = 320, 86
TEX_A, TEX_D = 256, 256      # angle x depth
DEPTH_K = 2200.0             # depth = K / radius
R_MIN = 3.0


def emit_bytes(name, data, extra_decls=""):
    lines = [
        "// Auto-generated by scripts/gen_tunnel_assets.py - do not edit.",
        "#include <stdint.h>", "",
        f"const uint8_t {name}[{len(data)}] = {{",
    ]
    for i in range(0, len(data), 24):
        lines.append("    " + "".join(f"0x{b:02x}," for b in data[i:i + 24]))
    lines += ["};", extra_decls, ""]
    (OUT_DIR / f"{name}.c").write_text("\n".join(lines))
    print(f"{name}: {len(data)} bytes")


def gen_lut():
    cx, cy = (HALF_W - 1) / 2.0, (HALF_H - 1) / 2.0
    data = bytearray()
    for hx in range(HALF_W):          # column-major: matches the blit scan
        for hy in range(HALF_H):
            dx, dy = hx - cx, hy - cy
            r = max(math.hypot(dx, dy), R_MIN)
            ang = int(math.atan2(dy, dx) / (2 * math.pi) * 256) & 0xFF
            dep = min(255, int(DEPTH_K / r))
            data.append(ang)
            data.append(dep)
    return data


def gen_tex():
    rnd = random.Random(7)
    data = bytearray()

    def pulse(x, period, sharp):
        # 0..1 peak at multiples of `period`, sharpened
        c = (math.cos(x * 2 * math.pi / period) + 1) / 2
        return c ** sharp

    for dep in range(TEX_D):
        for ang in range(TEX_A):
            ring = pulse(dep, 32, 6.0)
            spoke = pulse(ang, 32, 8.0)
            grid = max(ring, 0.75 * spoke)
            base = 0.10 + 0.06 * pulse(ang + dep, 8, 1.0)   # faint weave
            v = base + 0.9 * grid
            v += rnd.uniform(-0.02, 0.02)
            data.append(max(0, min(255, int(v * 255))))
    return data


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    emit_bytes("tunnel_lut", gen_lut())
    emit_bytes("tunnel_tex", gen_tex())
    (OUT_DIR / "tunnel_assets.h").write_text("\n".join([
        "// Auto-generated by scripts/gen_tunnel_assets.py - do not edit.",
        "#ifndef AV_TUNNEL_ASSETS_H",
        "#define AV_TUNNEL_ASSETS_H",
        "#include <stdint.h>",
        f"#define TUNNEL_HALF_W {HALF_W}",
        f"#define TUNNEL_HALF_H {HALF_H}",
        "// Column-major half-res LUT: entry i = hx*TUNNEL_HALF_H + hy,",
        "// bytes [2i] = angle, [2i+1] = depth.",
        f"extern const uint8_t tunnel_lut[{HALF_W * HALF_H * 2}];",
        "// Brightness texture, index = depth*256 + angle.",
        f"extern const uint8_t tunnel_tex[{TEX_A * TEX_D}];",
        "#endif",
        "",
    ]))
    print("header written")


if __name__ == "__main__":
    main()
