#!/usr/bin/env python3
"""Generate the radial-distance LUT for the plasma view.

Classic plasma: v = f(x) + g(y) + sin(dist + t). f/g are cheap 1-D arrays
rebuilt per frame; the per-pixel radial distance is precomputed here at half
resolution (320x86, column-major like the tunnel LUT) and stored in flash.

Output: src/ui/assets/plasma_dist.c (+ decl in plasma_assets.h).
"""

import math

from gen_vu_assets import OUT_DIR
from gen_tunnel_assets import emit_bytes

HALF_W, HALF_H = 320, 86
SCALE = 3.0   # distance units per half-pixel -> ring density


def main():
    cx, cy = (HALF_W - 1) / 2.0, (HALF_H - 1) / 2.0
    data = bytearray()
    for hx in range(HALF_W):
        for hy in range(HALF_H):
            d = math.hypot(hx - cx, hy - cy) * SCALE
            data.append(int(d) & 0xFF)
    emit_bytes("plasma_dist", data)
    (OUT_DIR / "plasma_assets.h").write_text("\n".join([
        "// Auto-generated by scripts/gen_plasma_assets.py - do not edit.",
        "#ifndef AV_PLASMA_ASSETS_H",
        "#define AV_PLASMA_ASSETS_H",
        "#include <stdint.h>",
        f"#define PLASMA_HALF_W {HALF_W}",
        f"#define PLASMA_HALF_H {HALF_H}",
        "// Column-major half-res radial distance, index = hx*PLASMA_HALF_H + hy.",
        f"extern const uint8_t plasma_dist[{HALF_W * HALF_H}];",
        "#endif",
        "",
    ]))
    print("header written")


if __name__ == "__main__":
    main()
