#!/usr/bin/env python3
"""Generate 7-segment LED clock assets for the clock view.

Renders one horizontal segment, one vertical segment and a colon dot as
glowing red LED shapes (hexagonal segments with baked bloom) at 3x and
downsamples. Digits are composed at runtime from 7 lv_img objects each;
unlit segments show the same image at low opacity for the classic LED
ghost-segment look.

Outputs: src/ui/assets/seg_h.c, seg_v.c, seg_dot.c (+ clock_assets.h).
Geometry constants are shared with the firmware through the header.
"""

from PIL import Image, ImageDraw, ImageFilter

from gen_vu_assets import OUT_DIR, emit_c

SS = 3

# Digit geometry (1x). A digit cell is DIGIT_W x DIGIT_H; segments are
# THICK wide with small inter-segment gaps and mitered (pointed) ends.
DIGIT_W = 96
DIGIT_H = 164
THICK   = 18
GAP     = 2
PAD     = 8          # glow bleed padding baked around each segment image

SEG_LEN_H = DIGIT_W - 2 * (THICK // 2) - 2 * GAP          # horizontal length
SEG_LEN_V = (DIGIT_H - 3 * THICK) // 2 + THICK - 2 * GAP  # vertical length
DOT_D     = 22

LED_CORE = (150, 205, 255)
LED_BODY = (28, 110, 250)
LED_GLOW = (10, 80, 255)


def hexagon(d, x0, y0, length, thick, horizontal, fill):
    t2 = thick / 2.0
    if horizontal:
        pts = [(x0, y0 + t2), (x0 + t2, y0), (x0 + length - t2, y0),
               (x0 + length, y0 + t2), (x0 + length - t2, y0 + thick),
               (x0 + t2, y0 + thick)]
    else:
        pts = [(x0 + t2, y0), (x0 + thick, y0 + t2),
               (x0 + thick, y0 + length - t2), (x0 + t2, y0 + length),
               (x0, y0 + length - t2), (x0, y0 + t2)]
    d.polygon(pts, fill=fill)


def render_segment(length, horizontal):
    w1 = (length + 2 * PAD) if horizontal else (THICK + 2 * PAD)
    h1 = (THICK + 2 * PAD) if horizontal else (length + 2 * PAD)
    W, H = w1 * SS, h1 * SS
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))

    # bloom layer
    glow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    hexagon(gd, PAD * SS, PAD * SS, length * SS, THICK * SS, horizontal,
            LED_GLOW + (255,))
    glow = glow.filter(ImageFilter.GaussianBlur(3.2 * SS))
    img.alpha_composite(glow)
    img.alpha_composite(glow)   # double for intensity

    # crisp body
    d = ImageDraw.Draw(img)
    hexagon(d, PAD * SS, PAD * SS, length * SS, THICK * SS, horizontal,
            LED_BODY + (255,))

    # hot core (inset; hexagon() always takes the LONG dimension as `length`)
    core_inset = THICK * SS // 3
    hexagon(d, PAD * SS + core_inset, PAD * SS + core_inset,
            length * SS - 2 * core_inset, THICK * SS - 2 * core_inset,
            horizontal, LED_CORE + (255,))

    return img.resize((w1, h1), Image.LANCZOS)


def render_dot():
    s1 = DOT_D + 2 * PAD
    S = s1 * SS
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    glow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    gd.ellipse([PAD * SS, PAD * SS, (PAD + DOT_D) * SS, (PAD + DOT_D) * SS],
               fill=LED_GLOW + (255,))
    glow = glow.filter(ImageFilter.GaussianBlur(3.2 * SS))
    img.alpha_composite(glow)
    img.alpha_composite(glow)
    d = ImageDraw.Draw(img)
    d.ellipse([PAD * SS, PAD * SS, (PAD + DOT_D) * SS, (PAD + DOT_D) * SS],
              fill=LED_BODY + (255,))
    ci = DOT_D * SS // 4
    d.ellipse([PAD * SS + ci, PAD * SS + ci,
               (PAD + DOT_D) * SS - ci, (PAD + DOT_D) * SS - ci],
              fill=LED_CORE + (255,))
    return img.resize((s1, s1), Image.LANCZOS)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    emit_c(render_segment(SEG_LEN_H, True), "seg_h", alpha=True)
    emit_c(render_segment(SEG_LEN_V, False), "seg_v", alpha=True)
    emit_c(render_dot(), "seg_dot", alpha=True)
    (OUT_DIR / "clock_assets.h").write_text("\n".join([
        "// Auto-generated by scripts/gen_clock_assets.py - do not edit.",
        "#ifndef AV_CLOCK_ASSETS_H",
        "#define AV_CLOCK_ASSETS_H",
        '#include "lvgl.h"',
        "extern const lv_img_dsc_t seg_h;",
        "extern const lv_img_dsc_t seg_v;",
        "extern const lv_img_dsc_t seg_dot;",
        f"#define SEG_DIGIT_W  {DIGIT_W}",
        f"#define SEG_DIGIT_H  {DIGIT_H}",
        f"#define SEG_THICK    {THICK}",
        f"#define SEG_GAP      {GAP}",
        f"#define SEG_PAD      {PAD}",
        f"#define SEG_LEN_H    {SEG_LEN_H}",
        f"#define SEG_LEN_V    {SEG_LEN_V}",
        f"#define SEG_DOT_D    {DOT_D}",
        "#endif",
        "",
    ]))
    print("header written")


if __name__ == "__main__":
    main()
