// Auto-generated by scripts/gen_clock_assets.py - do not edit.
#ifndef AV_CLOCK_ASSETS_H
#define AV_CLOCK_ASSETS_H
#include "lvgl.h"
extern const lv_img_dsc_t seg_h;
extern const lv_img_dsc_t seg_v;
extern const lv_img_dsc_t seg_dot;
#define SEG_DIGIT_W  96
#define SEG_DIGIT_H  164
#define SEG_THICK    18
#define SEG_GAP      2
#define SEG_PAD      8
#define SEG_LEN_H    74
#define SEG_LEN_V    69
#define SEG_DOT_D    22
#endif
