// Auto-generated by scripts/gen_plasma_assets.py - do not edit.
#ifndef AV_PLASMA_ASSETS_H
#define AV_PLASMA_ASSETS_H
#include <stdint.h>
#define PLASMA_HALF_W 320
#define PLASMA_HALF_H 86
// Column-major half-res radial distance, index = hx*PLASMA_HALF_H + hy.
extern const uint8_t plasma_dist[27520];
#endif
