// Auto-generated by scripts/gen_tunnel_assets.py - do not edit.
#ifndef AV_TUNNEL_ASSETS_H
#define AV_TUNNEL_ASSETS_H
#include <stdint.h>
#define TUNNEL_HALF_W 320
#define TUNNEL_HALF_H 86
// Column-major half-res LUT: entry i = hx*TUNNEL_HALF_H + hy,
// bytes [2i] = angle, [2i+1] = depth.
extern const uint8_t tunnel_lut[55040];
// Brightness texture, index = depth*256 + angle.
extern const uint8_t tunnel_tex[65536];
#endif
