// Auto-generated by scripts/gen_vu_assets.py - do not edit.
#ifndef AV_VU_ASSETS_H
#define AV_VU_ASSETS_H
#include "lvgl.h"
extern const lv_img_dsc_t vu_face;
extern const lv_img_dsc_t vu_needle;
extern const lv_img_dsc_t vu_hub;
#define VU_FACE_W 320
#define VU_FACE_H 172
#define VU_PIVOT_X 160
#define VU_PIVOT_Y 156
#define VU_NEEDLE_PIVOT_X 9
#define VU_NEEDLE_PIVOT_Y 128
#define VU_HUB_D 34
#define VU_ARC_HALF_DEG 43
#endif
